//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace skotstein.app.kinect.powerpoint_add_in {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class commands_de_DE {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal commands_de_DE() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("skotstein.app.kinect.powerpoint_add_in.commands_de_DE", typeof(commands_de_DE).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beende Gestensteuerung.
        /// </summary>
        internal static string cmd_end_recognition {
            get {
                return ResourceManager.GetString("cmd_end_recognition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beende Präsentation.
        /// </summary>
        internal static string cmd_end_slide_show {
            get {
                return ResourceManager.GetString("cmd_end_slide_show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Werde ich erkannt?.
        /// </summary>
        internal static string cmd_is_body_tracked {
            get {
                return ResourceManager.GetString("cmd_is_body_tracked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starte Gestensteuerung.
        /// </summary>
        internal static string cmd_start_recognition {
            get {
                return ResourceManager.GetString("cmd_start_recognition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starte Präsentation.
        /// </summary>
        internal static string cmd_start_slide_show {
            get {
                return ResourceManager.GetString("cmd_start_slide_show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was kann ich sagen?.
        /// </summary>
        internal static string cmd_voice_options {
            get {
                return ResourceManager.GetString("cmd_voice_options", resourceCulture);
            }
        }
    }
}
