//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace skotstein.app.kinect.powerpoint_add_in {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class voice_de_DE {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal voice_de_DE() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("skotstein.app.kinect.powerpoint_add_in.voice_de_DE", typeof(voice_de_DE).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie wurden nicht erkannt.
        /// </summary>
        internal static string voice_body_is_not_tracked {
            get {
                return ResourceManager.GetString("voice_body_is_not_tracked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie wurden erkannt.
        /// </summary>
        internal static string voice_body_is_tracked {
            get {
                return ResourceManager.GetString("voice_body_is_tracked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folgende Befehle stehen zur Auswahl:.
        /// </summary>
        internal static string voice_options {
            get {
                return ResourceManager.GetString("voice_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestenerkennung beendet.
        /// </summary>
        internal static string voice_recognition_ended {
            get {
                return ResourceManager.GetString("voice_recognition_ended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestenerkennung gestartet.
        /// </summary>
        internal static string voice_recognition_started {
            get {
                return ResourceManager.GetString("voice_recognition_started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Präsentation beendet.
        /// </summary>
        internal static string voice_slide_show_ended {
            get {
                return ResourceManager.GetString("voice_slide_show_ended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Präsentation gestartet.
        /// </summary>
        internal static string voice_slide_show_started {
            get {
                return ResourceManager.GetString("voice_slide_show_started", resourceCulture);
            }
        }
    }
}
